#!/bin/bash
libDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
source $libDir'/color'

gitbranch_name() {
  branch_id=$(git branch 2>/dev/null | grep '^*' | cut -c 3-)
  if [ $branch_id ]
  then
    printf $branch_id
  fi
}

virtualenv_name() {
  if [ -n "$VIRTUAL_ENV" ]; then
    printf "$(basename "$VIRTUAL_ENV")"
  fi
}

# Show kubernetes context
kubernetes_context() {
  if command -v kubectl >/dev/null 2>&1; then
    local k_ctx
    k_ctx=$(kubectl config current-context 2>/dev/null)
    if [ -n "$k_ctx" ]; then
      local k_ns
      k_ns=$(kubectl config view --minify --output 'jsonpath={..namespace}' 2>/dev/null)
      [ -z "$k_ns" ] && k_ns="default"
      printf "%s:%s" "$k_ctx" "$k_ns"
    fi
  fi
}

# Show docker context
docker_context() {
  if command -v docker >/dev/null 2>&1; then
    local d_ctx
    d_ctx=$(docker context show 2>/dev/null)
    if [ -n "$d_ctx" ]; then
      printf "%s" "$d_ctx"
    fi
  fi
}

function current_user() {
  if [ -n "$USER" ]; then
    printf "$USER"
  else
    printf "$USERNAME"
  fi
}

long_datetime() {
	TMP_DATE=$(date "+%A %d %B %Y %T")
	printf "$TMP_DATE"
}

short_datetime() {
	TMP_DATE=$(date "+%a %d %b %T")
	printf "$TMP_DATE"
}

long_date() {
  printf "$(date "+%A %d %B")"
}

short_date() {
	TMP_DATE=$(date "+%a %d %b")
	printf "$TMP_DATE"
}

short_time() {
  TMP_TIME=$(date "+%T")
	printf "$TMP_TIME"
}

common_datetime() {
  TMP_TIME=$(date "+%F %T")
	printf "$TMP_TIME"
}

# center_string() {
#   local string="$1"
#   local padding=$(( ($COLUMNS - ${#string}) / 2 ))
#   printf '%*s%s%*s\n' $padding '' "$string" $padding ''
# }

center_string() {
  local string="$1"
  local padding=$(( ($(tput cols) - ${#string}) / 2))
  printf '%*s%s%*s\n' $padding '' "$string" $padding ''
}
