#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
source $scriptDir'/../lib/lib'

prompt_cmd() {
  local git_branch
  git_branch=$(gitbranch_name)
  if [ -n "$git_branch" ]; then
    git_branch=" ($git_branch)"
  fi

  local venv_name
  venv_name=$(virtualenv_name)
  if [ -n "$venv_name" ]; then
    venv_name=" [$venv_name]"
  fi

  LINE_1="$(rgb_bg_ps1 $palette_primary_dark)$(no_color_ps1)"
  LINE_1+=" $(rgb_fg_ps1 $palette_secondary)$(common_datetime)"
  LINE_1+=" $(rgb_fg_ps1 $palette_accent)~"
  LINE_1+="$(rgb_fg_ps1 $palette_accent)${venv_name}"
  LINE_1+="$(rgb_fg_ps1 $palette_secondary_dark)${git_branch}"

  LINE_2="$(rgb_bg_ps1 $palette_primary_dark)$(no_color_ps1)"
  LINE_2+=" $(rgb_fg_ps1 $palette_secondary)$(current_user)@$HOSTNAME"
  LINE_2+="$(rgb_fg_ps1 $palette_primary):$(echo $PWD)"

  LINE_3="$(rgb_bg_ps1 $palette_primary_dark)$(no_color_ps1)"
  LINE_3+=" $(rgb_fg_ps1 $palette_accent)λ "
  LINE_3+="$(rgb_fg_ps1 $palette_text)"

  PS1="\r\n${LINE_1}\r\n${LINE_2}\r\n${LINE_3}"
}

export PROMPT_COMMAND='prompt_cmd'
