#!/bin/bash
palette_primary="#f6d878"         # Light Yellow
palette_primary_dark="#da9562"    # Orange
palette_secondary="#c0d66d"       # Lime Green
palette_secondary_dark="#a9cfbc"  # Muted Cyan
palette_accent="#8c6bc8"          # Purple
palette_accent_dark="#424242"     # Dark Gray
palette_gradient_start="#f6d878"  # Light Yellow
palette_gradient_end="#e2e22e"    # Bright Yellow
palette_variant_1="#8a0907"       # Dark Red
palette_variant_2="#750000"       # Darker Red
palette_variant_3="#680000"       # Darkest Red
palette_text="#f8f8f2"            # Off-white
